// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package app is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	RegisterInput
	RegisterResult
	DepositInput
	DepositResult
	ConsumeInput
	ConsumeResult
*/
package app

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterInput struct {
	CustomerId string `protobuf:"bytes,1,opt,name=customerId" json:"customerId,omitempty"`
}

func (m *RegisterInput) Reset()                    { *m = RegisterInput{} }
func (m *RegisterInput) String() string            { return proto.CompactTextString(m) }
func (*RegisterInput) ProtoMessage()               {}
func (*RegisterInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterInput) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type RegisterResult struct {
	AccountId int64 `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
}

func (m *RegisterResult) Reset()                    { *m = RegisterResult{} }
func (m *RegisterResult) String() string            { return proto.CompactTextString(m) }
func (*RegisterResult) ProtoMessage()               {}
func (*RegisterResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterResult) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type DepositInput struct {
	AccountId int64  `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
	Points    uint32 `protobuf:"varint,2,opt,name=points" json:"points,omitempty"`
}

func (m *DepositInput) Reset()                    { *m = DepositInput{} }
func (m *DepositInput) String() string            { return proto.CompactTextString(m) }
func (*DepositInput) ProtoMessage()               {}
func (*DepositInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DepositInput) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *DepositInput) GetPoints() uint32 {
	if m != nil {
		return m.Points
	}
	return 0
}

type DepositResult struct {
	CurPoints       uint32 `protobuf:"varint,1,opt,name=curPoints" json:"curPoints,omitempty"`
	DepositedPoints uint32 `protobuf:"varint,2,opt,name=depositedPoints" json:"depositedPoints,omitempty"`
}

func (m *DepositResult) Reset()                    { *m = DepositResult{} }
func (m *DepositResult) String() string            { return proto.CompactTextString(m) }
func (*DepositResult) ProtoMessage()               {}
func (*DepositResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DepositResult) GetCurPoints() uint32 {
	if m != nil {
		return m.CurPoints
	}
	return 0
}

func (m *DepositResult) GetDepositedPoints() uint32 {
	if m != nil {
		return m.DepositedPoints
	}
	return 0
}

type ConsumeInput struct {
	AccountId int64  `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
	Points    uint32 `protobuf:"varint,2,opt,name=points" json:"points,omitempty"`
}

func (m *ConsumeInput) Reset()                    { *m = ConsumeInput{} }
func (m *ConsumeInput) String() string            { return proto.CompactTextString(m) }
func (*ConsumeInput) ProtoMessage()               {}
func (*ConsumeInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ConsumeInput) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *ConsumeInput) GetPoints() uint32 {
	if m != nil {
		return m.Points
	}
	return 0
}

type ConsumeResult struct {
	CurPoints      uint32 `protobuf:"varint,1,opt,name=curPoints" json:"curPoints,omitempty"`
	ConsumedPoints uint32 `protobuf:"varint,2,opt,name=consumedPoints" json:"consumedPoints,omitempty"`
}

func (m *ConsumeResult) Reset()                    { *m = ConsumeResult{} }
func (m *ConsumeResult) String() string            { return proto.CompactTextString(m) }
func (*ConsumeResult) ProtoMessage()               {}
func (*ConsumeResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ConsumeResult) GetCurPoints() uint32 {
	if m != nil {
		return m.CurPoints
	}
	return 0
}

func (m *ConsumeResult) GetConsumedPoints() uint32 {
	if m != nil {
		return m.ConsumedPoints
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterInput)(nil), "app.RegisterInput")
	proto.RegisterType((*RegisterResult)(nil), "app.RegisterResult")
	proto.RegisterType((*DepositInput)(nil), "app.DepositInput")
	proto.RegisterType((*DepositResult)(nil), "app.DepositResult")
	proto.RegisterType((*ConsumeInput)(nil), "app.ConsumeInput")
	proto.RegisterType((*ConsumeResult)(nil), "app.ConsumeResult")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x89, 0x0b, 0x0b, 0x3b, 0x98, 0x15, 0x72, 0x90, 0x3d, 0x88, 0x2c, 0x39, 0x48, 0x4f,
	0xeb, 0xc1, 0x9f, 0x60, 0x2f, 0xbd, 0x95, 0x80, 0x78, 0xae, 0xe9, 0x50, 0x0a, 0x36, 0x09, 0x99,
	0xc9, 0xff, 0x17, 0x9b, 0x48, 0x6b, 0x0f, 0x22, 0xec, 0x31, 0x1f, 0xdf, 0x7b, 0x79, 0x30, 0x20,
	0x27, 0x24, 0xea, 0x06, 0xbc, 0x84, 0xe8, 0xd9, 0xab, 0x5d, 0x17, 0x82, 0x7e, 0x06, 0x69, 0x70,
	0x18, 0x89, 0x31, 0x36, 0x2e, 0x24, 0x56, 0x8f, 0x00, 0x36, 0x11, 0xfb, 0x09, 0x63, 0xd3, 0x9f,
	0xc4, 0x59, 0x54, 0x07, 0xb3, 0x22, 0xfa, 0x02, 0xc7, 0x9f, 0x80, 0x41, 0x4a, 0x9f, 0xac, 0x1e,
	0xe0, 0xd0, 0x59, 0xeb, 0x93, 0xe3, 0x12, 0xd8, 0x99, 0x05, 0xe8, 0x1a, 0x6e, 0x6b, 0x0c, 0x9e,
	0x46, 0xce, 0xfd, 0x7f, 0xda, 0xea, 0x1e, 0xf6, 0xc1, 0x8f, 0x8e, 0xe9, 0x74, 0x73, 0x16, 0x95,
	0x34, 0xe5, 0xa5, 0xdf, 0x41, 0x96, 0x96, 0xe5, 0x53, 0x9b, 0x62, 0x9b, 0x5d, 0x31, 0xbb, 0x0b,
	0x50, 0x15, 0xdc, 0xf5, 0x59, 0xc7, 0xbe, 0x5d, 0xf7, 0x6d, 0xf1, 0xf7, 0xbc, 0x57, 0xef, 0x28,
	0x4d, 0x78, 0xcd, 0xbc, 0x37, 0x90, 0xa5, 0xe5, 0x5f, 0xf3, 0x9e, 0xe0, 0x68, 0xb3, 0xfe, 0x7b,
	0xdd, 0x86, 0x7e, 0xec, 0xe7, 0x43, 0xbd, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x62, 0xe6,
	0x1e, 0xb9, 0x01, 0x00, 0x00,
}
