// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package app is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	RegisterInput
	RegisterResult
	DepositInput
	DepositResult
	ConsumeInput
	ConsumeResult
	FindResult
	Log
*/
package app

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterInput struct {
	CustomerId string `protobuf:"bytes,1,opt,name=customerId" json:"customerId,omitempty"`
}

func (m *RegisterInput) Reset()                    { *m = RegisterInput{} }
func (m *RegisterInput) String() string            { return proto.CompactTextString(m) }
func (*RegisterInput) ProtoMessage()               {}
func (*RegisterInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterInput) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type RegisterResult struct {
	AccountId int64 `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
}

func (m *RegisterResult) Reset()                    { *m = RegisterResult{} }
func (m *RegisterResult) String() string            { return proto.CompactTextString(m) }
func (*RegisterResult) ProtoMessage()               {}
func (*RegisterResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterResult) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type DepositInput struct {
	AccountId int64  `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
	Points    uint32 `protobuf:"varint,2,opt,name=points" json:"points,omitempty"`
}

func (m *DepositInput) Reset()                    { *m = DepositInput{} }
func (m *DepositInput) String() string            { return proto.CompactTextString(m) }
func (*DepositInput) ProtoMessage()               {}
func (*DepositInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DepositInput) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *DepositInput) GetPoints() uint32 {
	if m != nil {
		return m.Points
	}
	return 0
}

type DepositResult struct {
	CurPoints       uint32 `protobuf:"varint,1,opt,name=curPoints" json:"curPoints,omitempty"`
	DepositedPoints uint32 `protobuf:"varint,2,opt,name=depositedPoints" json:"depositedPoints,omitempty"`
}

func (m *DepositResult) Reset()                    { *m = DepositResult{} }
func (m *DepositResult) String() string            { return proto.CompactTextString(m) }
func (*DepositResult) ProtoMessage()               {}
func (*DepositResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DepositResult) GetCurPoints() uint32 {
	if m != nil {
		return m.CurPoints
	}
	return 0
}

func (m *DepositResult) GetDepositedPoints() uint32 {
	if m != nil {
		return m.DepositedPoints
	}
	return 0
}

type ConsumeInput struct {
	AccountId int64  `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
	Points    uint32 `protobuf:"varint,2,opt,name=points" json:"points,omitempty"`
}

func (m *ConsumeInput) Reset()                    { *m = ConsumeInput{} }
func (m *ConsumeInput) String() string            { return proto.CompactTextString(m) }
func (*ConsumeInput) ProtoMessage()               {}
func (*ConsumeInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ConsumeInput) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *ConsumeInput) GetPoints() uint32 {
	if m != nil {
		return m.Points
	}
	return 0
}

type ConsumeResult struct {
	CurPoints      uint32 `protobuf:"varint,1,opt,name=curPoints" json:"curPoints,omitempty"`
	ConsumedPoints uint32 `protobuf:"varint,2,opt,name=consumedPoints" json:"consumedPoints,omitempty"`
}

func (m *ConsumeResult) Reset()                    { *m = ConsumeResult{} }
func (m *ConsumeResult) String() string            { return proto.CompactTextString(m) }
func (*ConsumeResult) ProtoMessage()               {}
func (*ConsumeResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ConsumeResult) GetCurPoints() uint32 {
	if m != nil {
		return m.CurPoints
	}
	return 0
}

func (m *ConsumeResult) GetConsumedPoints() uint32 {
	if m != nil {
		return m.ConsumedPoints
	}
	return 0
}

type FindResult struct {
	AccountId  int64  `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
	CustomerId string `protobuf:"bytes,2,opt,name=customerId" json:"customerId,omitempty"`
	Points     uint32 `protobuf:"varint,3,opt,name=points" json:"points,omitempty"`
	Deposited  uint32 `protobuf:"varint,4,opt,name=deposited" json:"deposited,omitempty"`
	Consumed   uint32 `protobuf:"varint,5,opt,name=consumed" json:"consumed,omitempty"`
	Logs       []*Log `protobuf:"bytes,6,rep,name=logs" json:"logs,omitempty"`
	Created    int64  `protobuf:"varint,7,opt,name=created" json:"created,omitempty"`
}

func (m *FindResult) Reset()                    { *m = FindResult{} }
func (m *FindResult) String() string            { return proto.CompactTextString(m) }
func (*FindResult) ProtoMessage()               {}
func (*FindResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FindResult) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *FindResult) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *FindResult) GetPoints() uint32 {
	if m != nil {
		return m.Points
	}
	return 0
}

func (m *FindResult) GetDeposited() uint32 {
	if m != nil {
		return m.Deposited
	}
	return 0
}

func (m *FindResult) GetConsumed() uint32 {
	if m != nil {
		return m.Consumed
	}
	return 0
}

func (m *FindResult) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *FindResult) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type Log struct {
	Action  string `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Desc    string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	Created int64  `protobuf:"varint,4,opt,name=created" json:"created,omitempty"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Log) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Log) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Log) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterInput)(nil), "app.RegisterInput")
	proto.RegisterType((*RegisterResult)(nil), "app.RegisterResult")
	proto.RegisterType((*DepositInput)(nil), "app.DepositInput")
	proto.RegisterType((*DepositResult)(nil), "app.DepositResult")
	proto.RegisterType((*ConsumeInput)(nil), "app.ConsumeInput")
	proto.RegisterType((*ConsumeResult)(nil), "app.ConsumeResult")
	proto.RegisterType((*FindResult)(nil), "app.FindResult")
	proto.RegisterType((*Log)(nil), "app.log")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcd, 0x4a, 0xf4, 0x30,
	0x14, 0x86, 0xe9, 0xb4, 0xdf, 0xfc, 0x9c, 0xcf, 0x8e, 0x90, 0x85, 0x04, 0x19, 0x64, 0xc8, 0x42,
	0xba, 0xaa, 0xa0, 0x97, 0xe0, 0x20, 0x0c, 0x6e, 0x86, 0x80, 0xb8, 0x8e, 0x69, 0x28, 0x85, 0x4e,
	0x12, 0x9a, 0xe4, 0x4e, 0xbd, 0x20, 0x69, 0x9a, 0xfe, 0x4c, 0x17, 0x32, 0xe0, 0xae, 0xe7, 0xed,
	0x9b, 0xa7, 0x0f, 0x39, 0x85, 0xf4, 0x2c, 0x8c, 0x61, 0xa5, 0xc8, 0x75, 0xa3, 0xac, 0x42, 0x31,
	0xd3, 0x9a, 0x3c, 0x41, 0x4a, 0x45, 0x59, 0x19, 0x2b, 0x9a, 0xa3, 0xd4, 0xce, 0xa2, 0x07, 0x00,
	0xee, 0x8c, 0x55, 0x67, 0xd1, 0x1c, 0x0b, 0x1c, 0xed, 0xa3, 0x6c, 0x43, 0x27, 0x09, 0xc9, 0x61,
	0xdb, 0x1f, 0xa0, 0xc2, 0xb8, 0xda, 0xa2, 0x1d, 0x6c, 0x18, 0xe7, 0xca, 0x49, 0x1b, 0x0e, 0xc4,
	0x74, 0x0c, 0xc8, 0x01, 0x6e, 0x0e, 0x42, 0x2b, 0x53, 0xd9, 0x8e, 0xff, 0x6b, 0x1b, 0xdd, 0xc1,
	0x52, 0xab, 0x4a, 0x5a, 0x83, 0x17, 0xfb, 0x28, 0x4b, 0x69, 0x98, 0xc8, 0x27, 0xa4, 0x81, 0x32,
	0x7e, 0x94, 0xbb, 0xe6, 0xd4, 0x75, 0x23, 0xdf, 0x1d, 0x03, 0x94, 0xc1, 0x6d, 0xd1, 0xd5, 0x45,
	0x71, 0x9a, 0xf2, 0xe6, 0x71, 0xab, 0xf7, 0xaa, 0xa4, 0x71, 0x67, 0xf1, 0x17, 0xbd, 0x0f, 0x48,
	0x03, 0xe5, 0x2a, 0xbd, 0x47, 0xd8, 0xf2, 0xae, 0x7e, 0x69, 0x37, 0x4b, 0xc9, 0x77, 0x04, 0xf0,
	0x56, 0xc9, 0xe2, 0x9a, 0x8b, 0x9e, 0x2d, 0x6e, 0x31, 0x5f, 0xdc, 0xc4, 0x3d, 0x9e, 0xba, 0xb7,
	0xd4, 0xe1, 0x52, 0x70, 0xd2, 0xa9, 0x0e, 0x01, 0xba, 0x87, 0x75, 0x2f, 0x85, 0xff, 0xf9, 0x97,
	0xc3, 0x8c, 0x76, 0x90, 0xd4, 0xaa, 0x34, 0x78, 0xb9, 0x8f, 0xb3, 0xff, 0xcf, 0xeb, 0x9c, 0x69,
	0x9d, 0xd7, 0xaa, 0xa4, 0x3e, 0x45, 0x18, 0x56, 0xbc, 0x11, 0xac, 0xa5, 0xae, 0xbc, 0x6b, 0x3f,
	0x92, 0x77, 0x88, 0x6b, 0x55, 0xb6, 0x42, 0x8c, 0xdb, 0x4a, 0xc9, 0x20, 0x1b, 0x26, 0x84, 0x20,
	0x29, 0x84, 0xe1, 0x5e, 0x73, 0x43, 0xfd, 0xf3, 0x14, 0x96, 0x5c, 0xc0, 0xbe, 0x96, 0xfe, 0x67,
	0x7e, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x41, 0x8e, 0x9a, 0xdd, 0x02, 0x00, 0x00,
}
